version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Installing angular cli...
      - npm install -g @angular/cli
      - npm add @angular-devkit/build-angular --dev
      - npm add @angular-devkit/build-angular --dev
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
    files:
        - '**/*'
#     base-directory: 'dist/**/*'
    discard-paths: yes
    
#     artifacts:
#   files:
#     - index.html
#     - dist/**/*
#     - node_modules/**/*
